[project]
name = "aidb-tui"
version = "0.1.0"
description = "AI Daily Briefing - Terminal User Interface"
requires-python = ">=3.12"
dependencies = [
    "typer>=0.12.0",
    "rich>=13.0.0",
    "aidb-ai",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.sdist]
include = ["src/"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[project.scripts]
aidb = "aidb_tui.main:main"

[tool.uv.sources]
aidb-ai = { workspace = true }