[project]
name = "aidb-ai"
version = "0.1.0"
description = "AI Daily Briefing - Core AI Models and Services"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.0.0",
    "pydantic-ai>=0.0.14",
    "google-generativeai>=0.8.3",
    "httpx>=0.25.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]